Require Approver Comment and Allow Updating Approver Comments
FINRAOS/Gatekeeper pull request #202
Opened 2023-02-02 16:26 UTC by Colin-Schultz

2023-02-02 17:00 UTC, r331 commented on services/rds/src/main/java/org/finra/gatekeeper/services/accessrequest/AccessRequestService.java
> +    public List<ActiveAccessRequestWrapper> updateRequestApproverComment(String taskId, Long requestId, String approverComments ) {
unused variable - taskId

2023-02-02 19:13 UTC, SMxJrz requested changes

2023-02-02 19:13 UTC, SMxJrz commented on services/rds/src/main/java/org/finra/gatekeeper/controllers/AccessRequestController.java
> +    @RequestMapping(value = "/updateRequestApproverComment", method = RequestMethod.PUT, produces = MediaType.APPLICATION_JSON_VALUE)
I Know we're only going to be allowing the request approver comment at this point Can we keep the name of this more general? like "updateRequest"

2023-02-02 19:13 UTC, SMxJrz commented on services/rds/src/main/java/org/finra/gatekeeper/services/accessrequest/AccessRequestService.java
> +    public List<ActiveAccessRequestWrapper> updateRequestApproverComment(Long requestId, String approverComments ) {
comment in Controller class applies here too

2023-02-02 19:13 UTC, SMxJrz commented on ui/app/component/shared/RequestDataService.js
> +        this.updateRequest = 'updateRequestApproverComment';
same as other comment

2023-02-02 19:13 UTC, SMxJrz commented on ui/app/component/shared/RequestDataService.js
> +    updateRequestApproverComment(request){
same as other comment

2023-02-03 16:03 UTC, SMxJrz approved these changes

2023-02-03 16:03 UTC, merged